name: .NET

on:
  
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Package
      if: github.ref == 'refs/heads/master'
      run: dotnet pack -c Release -o . GrpcBrowser/GrpcBrowser.csproj
    - name: Publish
      if: github.ref == 'refs/heads/master'
      run: dotnet nuget push src/GrpcBrowser/*.nupkg -k ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json
      
      
